version: 2.1

jobs:
  test:
    docker:
      - image: jmarpledev/model_compression
    steps:
      - checkout
      - run: make dev
      - run: make test

workflows:
  main:
    jobs:
      - test
