# densenet // L=190, k=40, num_classes=100
'4b4138adc4235cdfa0c360ddb6467870f4ca6df7f4e22704b65c08cc':
    dir_name: densenet_large_numclasses_100
    file_name: model_best.pth.tar
    link: https://drive.google.com/u/0/uc?export=download&confirm=ilUf&id=1Mwr6pmdWN7r4wgmE1nYqEUDyuwLt5ce5
# simplenet // num_classes=100
'e3a038efe3aa38ac295c43454bb993040f5087617c44ee6116142b28': 
    dir_name: simplenet_numclasses_100
    file_name: model_best.pth.tar
    link: https://drive.google.com/u/0/uc?id=12rKUVZNDucVfxi4G3fLJwahF2dxKDOfZ&export=download
