name: format-lint

on: push

jobs:
  format-lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: model_compression
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Format with black, isort
      shell: bash -l {0}
      run: make format
    - name: Lint with pylint, mypy, flake8 using pytest
      shell: bash -l {0}
      run: make test
